sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker build -t py-tesseract4 .
  - docker tag py-tesseract4 $DOCKER_USERNAME/py-tesseract4
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/py-tesseract4:latest
